BASE_URL = 'https://api.openbrewerydb.org/breweries'

SINGLE_BREWERY = '/'
LIST_BREWERIES = '/'
RANDOM = '/random'
SEARCH = '/search'
AUTOCOMPLETE = '/autocomplete'

QUERY_PARAMETER = 'query'
SORT_BY_CITY_PARAMETER = 'by_city'
FILTER_BY_DISTANCE_PARAMETER = 'by_dist'
FILTER_BY_NAME_PARAMETER = 'by_name'
FILTER_BY_STATE_PARAMETER = 'by_state'
FILTER_BY_POSTAL_CODE_PARAMETER = 'by_postal'
FILTER_BY_TYPE_PARAMETER = 'by_type'
OFFSET_OR_PAGE_PARAMETER = 'page'
PER_PAGE_PARAMETER = 'per_page'
